from __future__ import annotations

import csv
import io
import zipfile
from email.message import EmailMessage
from pathlib import Path

import pytest
from flask import Flask
from openpyxl import Workbook

import asset_compensation.services.email_upload_service as email_upload_module
import asset_compensation.services.supplier_upload_service as supplier_upload_module
from asset_compensation.config import Settings
from asset_compensation.parsers import EmlParseError, load_supplier_records, parse_money
from asset_compensation.services.supplier_upload_service import SupplierUploadService
from asset_compensation.web import create_app


@pytest.fixture
def upload_app(tmp_path: Path) -> Flask:
    application = create_app(
        Settings(
            data_dir=tmp_path / "runtime",
            demo_mode=False,
            secret_key="synthetic-upload-test-key",
        )
    )
    application.config.update(TESTING=True)
    yield application
    application.extensions["asset_hub"]["repository"].close()


def _supplier_csv(rows: list[tuple[str, str, str, str]]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.writer(stream)
    writer.writerow(
        ["Domain", "Supplier Number", "Supplier Site", "Supplier Name", "Address"]
    )
    for domain, number, site, name in rows:
        writer.writerow([domain, number, site, name, "not retained"])
    return stream.getvalue().encode()


def _oracle_bip_xls(rows: list[tuple[str, str, str, str]]) -> bytes:
    headers = ["Supplier number", "Supplier Name", "Supplier Site", "Employee Number"]
    html_rows = [
        "<tr>" + "".join(f"<td>{value}</td>" for value in headers) + "</tr>"
    ]
    html_rows.extend(
        "<tr>" + "".join(f"<td>{value}</td>" for value in row) + "</tr>"
        for row in rows
    )
    return (
        "<html><!-- Generated by Oracle BI Publisher 10.1.3.4.2 -->"
        "<body><table>"
        + "".join(html_rows)
        + "</table></body></html>"
    ).encode()


def _supplier_xlsx(rows: list[tuple[str, str, str, str]]) -> bytes:
    workbook = Workbook()
    sheet = workbook.active
    sheet.append(["Domain", "Supplier Number", "Supplier Site", "Supplier Name"])
    for row in rows:
        sheet.append(row)
    stream = io.BytesIO()
    workbook.save(stream)
    workbook.close()
    return stream.getvalue()


def _upload_supplier_pair(
    client: object,
    active: bytes,
    inactive: bytes,
    *,
    active_name: str = "active.csv",
    inactive_name: str = "inactive.csv",
    active_type: str = "text/csv",
    inactive_type: str = "text/csv",
    header: str | None = "supplier-v1",
) -> object:
    headers = {"X-Asset-Hub-Upload": header} if header is not None else {}
    return client.post(  # type: ignore[attr-defined]
        "/api/suppliers/upload",
        data={
            "active_file": (io.BytesIO(active), active_name, active_type),
            "inactive_file": (io.BytesIO(inactive), inactive_name, inactive_type),
        },
        headers=headers,
        content_type="multipart/form-data",
    )


def _damaged_eml(
    domain: str = "demo.user",
    *,
    asset: str = "DEMO-LAP-901",
    message_id: str = "synthetic-upload@example.invalid",
    amount: str = "123.456",
) -> bytes:
    message = EmailMessage()
    message["Subject"] = (
        f"[Đền bù] : IT - Thông tin tài sản hư hỏng - {asset} - {domain}"
    )
    message["From"] = "Synthetic Asset Team <asset@example.invalid>"
    message["To"] = f"Synthetic User <{domain}@example.invalid>"
    message["Date"] = "Thu, 13 Aug 2026 03:49:56 +0000"
    message["Message-ID"] = f"<{message_id}>"
    message.set_content(
        f"Người dùng : {domain} - đồng ý đền bù\n"
        f"Chi phí đền bù : {amount} VNĐ\n"
        f"Mã thiết bị : {asset}\n"
        "Hư hỏng: synthetic damage"
    )
    return message.as_bytes()


def _lost_eml(*, with_asset_row: bool) -> bytes:
    message = EmailMessage()
    message["Subject"] = (
        "IT - Thông tin tài sản thất lạc - MOU16902 - demo.lost"
    )
    message["From"] = "Synthetic Asset Team <asset@example.invalid>"
    message["To"] = "Synthetic Lost User <demo.lost@example.invalid>"
    message["Date"] = "Thu, 13 Aug 2026 03:49:56 +0000"
    message["Message-ID"] = (
        "<synthetic-lost-row@example.invalid>"
        if with_asset_row
        else "<synthetic-lost-no-row@example.invalid>"
    )
    if with_asset_row:
        body = """
        Asset Name Product Name Domain Ngày bắt đầu sử dụng Ngày thất lạc/mất
        Nguyên giá ban đầu Mức khấu hao sử dụng còn lại Phí đền bù trách nhiệm
        Tổng số tiền đền bù
        MOU16902 Demo Wireless Pointer demo.lost 06/04/2026 04/08/2026
        345,678 234,567 12,345 246,912
        """
    else:
        body = """
        Người quản lý thiết bị: demo.lost
        Mã thiết bị: MOU16902
        Phí đền bù trách nhiệm khi mất thiết bị.
        Total:
        234,567
        12,345
        246,912
        """
    message.set_content(body)
    return message.as_bytes()


def _lost_eml_with_money_token(token: str) -> bytes:
    message = EmailMessage()
    message["Subject"] = "IT - Thông báo mất thiết bị - MOU16999 - demo.money"
    message["From"] = "Synthetic Asset Team <asset@example.invalid>"
    message["To"] = "Synthetic User <demo.money@example.invalid>"
    message["Date"] = "Thu, 13 Aug 2026 03:49:56 +0000"
    message["Message-ID"] = "<synthetic-invalid-money@example.invalid>"
    message.set_content(
        "Người quản lý thiết bị: demo.money\n"
        "Mã thiết bị: MOU16999\n"
        "Phí đền bù trách nhiệm khi mất thiết bị.\n"
        f"Total:\n{token}\n2\n3"
    )
    return message.as_bytes()


def _upload_emails(
    client: object,
    files: list[tuple[bytes, str]],
    *,
    header: str | None = "email-v1",
) -> object:
    headers = {"X-Asset-Hub-Upload": header} if header is not None else {}
    return client.post(  # type: ignore[attr-defined]
        "/api/emails/upload",
        data={
            "files": [
                (io.BytesIO(content), filename, "message/rfc822")
                for content, filename in files
            ]
        },
        headers=headers,
        content_type="multipart/form-data",
    )


def test_supplier_upload_activates_data_minimized_atomic_directory(
    upload_app: Flask,
) -> None:
    client = upload_app.test_client()
    response = _upload_supplier_pair(
        client,
        _supplier_csv([("demo.active", "000101", "01", "Synthetic Active")]),
        _supplier_csv([("demo.inactive", "000202", "02", "Synthetic Inactive")]),
        active_name="../../private-active.csv",
        inactive_name=r"C:\private\inactive.csv",
    )

    assert response.status_code == 201
    payload = response.get_json()
    assert payload["total_count"] == 2
    assert payload["active_count"] == 1
    assert payload["inactive_count"] == 1
    assert payload["collision_count"] == 0

    reference = upload_app.extensions["asset_hub"]["settings"].reference_dir
    versions = list((reference / "supplier-versions").iterdir())
    assert len(versions) == 1
    assert {item.name for item in versions[0].iterdir()} == {
        "directory.csv",
        "metadata.json",
    }
    normalized = (versions[0] / "directory.csv").read_text("utf-8")
    assert "not retained" not in normalized
    assert not list(reference.rglob("active.csv"))
    assert not list(reference.rglob("inactive.csv"))


@pytest.mark.parametrize("header", [None, "wrong-version"])
def test_supplier_upload_requires_csrf_header(upload_app: Flask, header: str | None) -> None:
    response = _upload_supplier_pair(
        upload_app.test_client(),
        _supplier_csv([("demo.active", "1", "01", "Active")]),
        _supplier_csv([("demo.inactive", "2", "02", "Inactive")]),
        header=header,
    )

    assert response.status_code == 400
    assert "header" in response.get_json()["error"].casefold()


def test_supplier_upload_reports_and_excludes_ambiguous_domains(upload_app: Flask) -> None:
    response = _upload_supplier_pair(
        upload_app.test_client(),
        _supplier_csv([("Demo.Collision", "000101", "01", "First")]),
        _supplier_csv([("demo.collision@example.com", "000202", "02", "Second")]),
    )

    assert response.status_code == 201
    payload = response.get_json()
    assert payload["review_required"] is True
    assert payload["collision_count"] == 1
    assert payload["collisions"][0]["domain"] == "demo.collision"
    assert payload["total_count"] == 0
    directory = upload_app.extensions["asset_hub"][
        "supplier_upload_service"
    ].load_directory()
    assert directory == {}


def test_supplier_upload_does_not_prefer_active_on_status_conflict(
    upload_app: Flask,
) -> None:
    same_row = [("demo.status", "000101", "01", "Same Person")]

    response = _upload_supplier_pair(
        upload_app.test_client(),
        _supplier_csv(same_row),
        _supplier_csv(same_row),
    )

    payload = response.get_json()
    assert response.status_code == 201
    assert payload["collision_count"] == 1
    assert payload["total_count"] == 0
    assert "status identities" in payload["collisions"][0]["message"]
    assert upload_app.extensions["asset_hub"][
        "supplier_upload_service"
    ].load_directory() == {}


def test_supplier_upload_enforces_aggregate_file_limit(
    upload_app: Flask, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(supplier_upload_module, "MAX_SUPPLIER_TOTAL_BYTES", 100)
    response = _upload_supplier_pair(
        upload_app.test_client(),
        _supplier_csv([("demo.active", "1", "01", "Active")]),
        _supplier_csv([("demo.inactive", "2", "02", "Inactive")]),
    )

    assert response.status_code == 400
    assert "total limit" in response.get_json()["error"]


def test_oracle_bip_upload_derives_domain_from_supplier_name_not_employee_number(
    upload_app: Flask,
) -> None:
    active = _oracle_bip_xls(
        [
            ("000101", "Synthetic Person-demo.user", "01", "VG-15277"),
            ("000999", "No safe suffix", "09", "VG-99999"),
        ]
    )
    inactive = _oracle_bip_xls(
        [("000202", "Former Person-demo.former", "02", "VG-25277")]
    )

    response = _upload_supplier_pair(
        upload_app.test_client(),
        active,
        inactive,
        active_name="Supplier Active.xls",
        inactive_name="Supplier Inactive.xls",
        active_type="application/vnd.ms-excel",
        inactive_type="application/vnd.ms-excel",
    )

    assert response.status_code == 201
    payload = response.get_json()
    assert payload["active_count"] == 1
    assert any("safe Supplier Name domain suffix" in item for item in payload["warnings"])
    directory = upload_app.extensions["asset_hub"][
        "supplier_upload_service"
    ].load_directory()
    assert set(directory) == {"demo.user", "demo.former"}
    assert "vg-15277" not in directory


def test_supplier_pair_over_20k_rows_roundtrips_and_enriches_email(
    upload_app: Flask,
) -> None:
    """The trusted merged directory may contain up to two source files of rows."""

    active_rows = [
        (f"bulk.active.{index}", f"A{index:05d}", "01", "Synthetic Active")
        for index in range(10_001)
    ]
    inactive_rows = [
        (f"bulk.inactive.{index}", f"I{index:05d}", "02", "Synthetic Inactive")
        for index in range(10_001)
    ]
    client = upload_app.test_client()

    supplier = _upload_supplier_pair(
        client,
        _supplier_csv(active_rows),
        _supplier_csv(inactive_rows),
    )
    email = _upload_emails(
        client,
        [
            (
                _damaged_eml(
                    "bulk.active.0",
                    message_id="synthetic-large-directory@example.invalid",
                ),
                "synthetic.eml",
            )
        ],
    )

    assert supplier.status_code == 201
    assert supplier.get_json()["total_count"] == 20_002
    assert email.status_code == 200
    assert email.get_json()["ingested"] == 1
    case = client.get(f"/api/cases/{email.get_json()['case_ids'][0]}").get_json()["case"]
    assert case["supplier_number"] == "A00000"


def test_supplier_upload_supports_real_xlsx_content(upload_app: Flask) -> None:
    response = _upload_supplier_pair(
        upload_app.test_client(),
        _supplier_xlsx([("demo.xlsx", "000301", "03", "XLSX Person")]),
        _supplier_xlsx([("demo.oldxlsx", "000302", "04", "Old XLSX Person")]),
        active_name="active.xlsx",
        inactive_name="inactive.xlsx",
        active_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        inactive_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )

    assert response.status_code == 201
    assert response.get_json()["total_count"] == 2


def test_supplier_upload_rejects_xlsx_active_content(upload_app: Flask) -> None:
    source = io.BytesIO(_supplier_xlsx([("demo.xlsx", "1", "01", "Person")]))
    modified = io.BytesIO()
    with zipfile.ZipFile(source) as original, zipfile.ZipFile(modified, "w") as target:
        for item in original.infolist():
            target.writestr(item, original.read(item.filename))
        target.writestr("xl/vbaProject.bin", b"synthetic macro marker")

    response = _upload_supplier_pair(
        upload_app.test_client(),
        modified.getvalue(),
        _supplier_xlsx([("demo.old", "2", "02", "Old")]),
        active_name="active.xlsx",
        inactive_name="inactive.xlsx",
        active_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        inactive_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )

    assert response.status_code == 400
    assert "active or embedded content" in response.get_json()["error"]


def test_supplier_upload_rejects_xlsx_external_relationship(upload_app: Flask) -> None:
    source = io.BytesIO(_supplier_xlsx([("demo.xlsx", "1", "01", "Person")]))
    modified = io.BytesIO()
    with zipfile.ZipFile(source) as original, zipfile.ZipFile(modified, "w") as target:
        for item in original.infolist():
            target.writestr(item, original.read(item.filename))
        target.writestr(
            "xl/worksheets/_rels/sheet1.xml.rels",
            b"""<?xml version="1.0" encoding="UTF-8"?>
            <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
              <Relationship Id="rId99" Type="synthetic" Target="https://example.invalid/"
                            TargetMode="External" />
            </Relationships>""",
        )

    response = _upload_supplier_pair(
        upload_app.test_client(),
        modified.getvalue(),
        _supplier_xlsx([("demo.old", "2", "02", "Old")]),
        active_name="active.xlsx",
        inactive_name="inactive.xlsx",
        active_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        inactive_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )

    assert response.status_code == 400
    assert "external relationship" in response.get_json()["error"]


def test_failed_supplier_replacement_leaves_previous_version_active(upload_app: Flask) -> None:
    client = upload_app.test_client()
    first = _upload_supplier_pair(
        client,
        _supplier_csv([("demo.first", "1", "01", "First")]),
        _supplier_csv([("demo.old", "2", "02", "Old")]),
    )
    previous_status = client.get("/api/suppliers/status").get_json()["status"]
    failed = _upload_supplier_pair(
        client,
        _supplier_csv([("demo.replacement", "3", "03", "Replacement")]),
        b"not an xlsx",
        inactive_name="inactive.xlsx",
        inactive_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )

    assert first.status_code == 201
    assert failed.status_code == 400
    current_status = client.get("/api/suppliers/status").get_json()["status"]
    assert current_status["updated_at"] == previous_status["updated_at"]
    directory = upload_app.extensions["asset_hub"][
        "supplier_upload_service"
    ].load_directory()
    assert set(directory) == {"demo.first", "demo.old"}


def test_supplier_service_purges_only_stale_private_staging(tmp_path: Path) -> None:
    reference = tmp_path / "reference"
    stale = reference / "supplier-staging-abcd1234"
    unrelated = reference / "supplier-staging"
    stale.mkdir(parents=True)
    unrelated.mkdir()
    (stale / "active.xls").write_bytes(b"private synthetic marker")

    SupplierUploadService(reference)

    assert not stale.exists()
    assert unrelated.is_dir()


def test_email_upload_ingests_immediately_with_uploaded_supplier(upload_app: Flask) -> None:
    client = upload_app.test_client()
    supplier = _upload_supplier_pair(
        client,
        _supplier_csv([("demo.user", "000101", "01", "Synthetic User")]),
        _supplier_csv([("demo.former", "000202", "02", "Synthetic Former")]),
    )
    assert supplier.status_code == 201

    response = _upload_emails(
        client,
        [(_damaged_eml(), r"..\..\private damaged.eml")],
    )

    assert response.status_code == 200
    payload = response.get_json()
    assert payload["received_count"] == 1
    assert payload["ingested"] == 1
    assert payload["case_types"] == {"DAMAGED": 1}
    assert set(payload["cases"][0]) == {"id", "case_type"}
    case = client.get(f"/api/cases/{payload['case_ids'][0]}").get_json()["case"]
    assert case["supplier_number"] == "000101"
    assert case["supplier_site"] == "01"
    assert case["source_file"] == "upload-01.eml"
    assert len(case["metadata"]["content_sha256"]) == 64
    assert len(case["metadata"]["message_id_sha256"]) == 64
    assert {"message_id", "sender", "subject"}.isdisjoint(case["metadata"])


@pytest.mark.parametrize("header", [None, "wrong-version"])
def test_email_upload_rejects_invalid_csrf_header(
    upload_app: Flask, header: str | None
) -> None:
    client = upload_app.test_client()
    response = _upload_emails(client, [(_damaged_eml(), "case.eml")], header=header)

    assert response.status_code == 400
    assert "header" in response.get_json()["error"].casefold()


def test_email_upload_rejects_non_email_content_without_leaking_it(upload_app: Flask) -> None:
    client = upload_app.test_client()
    marker = "RAW-SUBJECT-MUST-NOT-LEAK"
    invalid = _upload_emails(
        client,
        [(f"Subject: {marker}\n\nnot enough headers".encode(), "invalid.eml")],
    )

    assert invalid.status_code == 400
    assert marker not in invalid.get_data(as_text=True)


def test_email_upload_rejects_real_attachments(upload_app: Flask) -> None:
    message = EmailMessage()
    message["Subject"] = "Synthetic damaged asset"
    message["From"] = "sender@example.invalid"
    message["To"] = "receiver@example.invalid"
    message.set_content("damaged asset DEMO-LAP-901")
    message.add_attachment(
        b"synthetic archive",
        maintype="application",
        subtype="zip",
        filename="evidence.zip",
    )

    response = _upload_emails(
        upload_app.test_client(), [(message.as_bytes(), "attachment.eml")]
    )

    assert response.status_code == 400
    assert "attachments" in response.get_json()["error"]


def test_email_upload_enforces_file_count_and_size_limits(
    upload_app: Flask, monkeypatch: pytest.MonkeyPatch
) -> None:
    client = upload_app.test_client()
    too_many = _upload_emails(
        client,
        [(_damaged_eml(message_id=f"message-{index}@example.invalid"), f"{index}.eml")
         for index in range(21)],
    )
    monkeypatch.setattr(email_upload_module, "MAX_EMAIL_FILE_BYTES", 100)
    too_large = _upload_emails(client, [(_damaged_eml(), "large.eml")])

    assert too_many.status_code == 400
    assert "more than 20" in too_many.get_json()["error"]
    assert too_large.status_code == 400
    assert "2 MiB per-file limit" in too_large.get_json()["error"]


def test_email_message_id_conflict_is_not_silently_overwritten(upload_app: Flask) -> None:
    client = upload_app.test_client()
    first = _upload_emails(client, [(_damaged_eml(amount="100.000"), "first.eml")])
    conflict = _upload_emails(client, [(_damaged_eml(amount="200.000"), "second.eml")])

    assert first.get_json()["ingested"] == 1
    payload = conflict.get_json()
    assert payload["ingested"] == 0
    assert payload["unknown_files"] == ["upload-01.eml"]
    assert any("Message-ID" in warning for warning in payload["warnings"])
    case = client.get(f"/api/cases/{first.get_json()['case_ids'][0]}").get_json()["case"]
    assert case["amount"] == 100000


def test_lost_email_keeps_trannnb_metadata_without_inventing_missing_source(
    upload_app: Flask,
) -> None:
    client = upload_app.test_client()
    with_row = _upload_emails(client, [(_lost_eml(with_asset_row=True), "row.eml")])
    without_row = _upload_emails(
        client, [(_lost_eml(with_asset_row=False), "without-row.eml")]
    )

    row_case = client.get(f"/api/cases/{with_row.get_json()['case_ids'][0]}").get_json()[
        "case"
    ]
    no_row_case = client.get(
        f"/api/cases/{without_row.get_json()['case_ids'][0]}"
    ).get_json()["case"]
    assert row_case["metadata"]["usage_start"] == "06/04/2026"
    assert row_case["metadata"]["loss_date"] == "04/08/2026"
    assert row_case["metadata"]["original_value"] == 345678
    assert {"usage_start", "loss_date", "original_value"}.isdisjoint(
        no_row_case["metadata"]
    )


def test_malformed_or_oversized_money_is_rejected_without_500_or_raw_leak(
    upload_app: Flask,
) -> None:
    client = upload_app.test_client()
    malformed_token = "1..2"
    malformed = _upload_emails(
        client,
        [(_lost_eml_with_money_token(malformed_token), "malformed.eml")],
    )
    oversized = _upload_emails(
        client,
        [(_damaged_eml(amount="10000000000000000"), "oversized.eml")],
    )

    assert malformed.status_code == 200
    assert malformed.get_json()["ingested"] == 0
    assert malformed.get_json()["unknown_files"] == ["upload-01.eml"]
    assert malformed_token not in malformed.get_data(as_text=True)
    assert oversized.status_code == 200
    assert oversized.get_json()["ingested"] == 0
    assert client.get("/api/dashboard").get_json()["summary"]["total"] == 0


@pytest.mark.parametrize("token", ["1,.2", "1,2.3", "12.34", "1..000"])
def test_money_parser_rejects_mixed_or_malformed_grouping(token: str) -> None:
    with pytest.raises(EmlParseError, match="invalid monetary"):
        parse_money(token)


def test_uploaded_collision_marks_matching_email_as_ambiguous(upload_app: Flask) -> None:
    client = upload_app.test_client()
    supplier = _upload_supplier_pair(
        client,
        _supplier_csv([("demo.user", "000101", "01", "First")]),
        _supplier_csv([("demo.user", "000202", "02", "Second")]),
    )
    assert supplier.get_json()["collision_count"] == 1

    email = _upload_emails(client, [(_damaged_eml(), "ambiguous.eml")])
    case = client.get(f"/api/cases/{email.get_json()['case_ids'][0]}").get_json()["case"]

    assert any("ambiguous across multiple" in warning for warning in case["warnings"])
    assert case["supplier_number"] is None


def test_supplier_parser_rejects_structurally_wide_rows(tmp_path: Path) -> None:
    path = tmp_path / "wide.csv"
    headers = ["Domain", "Supplier Number", "Supplier Site", *[f"Extra {i}" for i in range(30)]]
    path.write_text(",".join(headers) + "\n" + ",".join(["x"] * len(headers)), "utf-8")

    with pytest.raises(ValueError, match="32-column"):
        load_supplier_records(path)


def test_oracle_parser_stops_at_data_row_limit(tmp_path: Path) -> None:
    path = tmp_path / "too-many.xls"
    row = ("1", "Synthetic Person-demo.user", "01", "VG-1")
    path.write_bytes(_oracle_bip_xls([row] * 20_001))

    with pytest.raises(ValueError, match="20,000-row"):
        load_supplier_records(path)
