"""External format and automation adapters."""

from .accounting_template import (
    ACCOUNTING_TEMPLATE_HEADERS,
    AccountingTemplateAdapter,
    AccountingTemplateExportResult,
)
from .accounting_xlsx import (
    AccountingExportError,
    AccountingExportResult,
    AccountingValidationError,
    AccountingXlsxAdapter,
    GlAccountPair,
    OutputExistsError,
)
from .pdf import (
    EmlPdfConverter,
    PdfAdapterError,
    PdfCapabilityError,
    PdfDependencyError,
    PdfMerger,
    PdfNormalizationResult,
    PdfOverflowPolicy,
    PdfPageNormalizer,
    PdfPageOverflowError,
    PreparedEmlDocument,
    PypdfMerger,
    PypdfPageNormalizer,
    WeasyPrintPdfConverter,
    WordPdfConverter,
    prepare_eml_bytes,
    prepare_eml_document,
)
from .tran_mail import (
    TRAN_MAIL_HEADERS,
    TranMailDraftBuilder,
    TranMailDraftResult,
    TranMailError,
    build_tran_mail_table,
)
from .tran_reference_xlsx import (
    CcdcClassification,
    CcdcClassificationLookup,
    CcdcWorkbookIndex,
    FaGlLookup,
    FaGlRecord,
    FaGlWorkbookIndex,
    TranReferenceError,
)
from .tran_workbook import (
    TRAN_SENT_HEADERS,
    TRAN_YEAR_HEADERS,
    TranWorkbookAdapter,
    TranWorkbookError,
    TranWorkbookExportResult,
    remaining_value_excel_formula,
)

__all__ = [
    "AccountingExportError",
    "AccountingExportResult",
    "AccountingTemplateAdapter",
    "AccountingTemplateExportResult",
    "AccountingValidationError",
    "AccountingXlsxAdapter",
    "ACCOUNTING_TEMPLATE_HEADERS",
    "EmlPdfConverter",
    "GlAccountPair",
    "OutputExistsError",
    "PdfAdapterError",
    "PdfCapabilityError",
    "PdfDependencyError",
    "PdfMerger",
    "PdfNormalizationResult",
    "PdfOverflowPolicy",
    "PdfPageNormalizer",
    "PdfPageOverflowError",
    "PreparedEmlDocument",
    "PypdfMerger",
    "PypdfPageNormalizer",
    "WeasyPrintPdfConverter",
    "WordPdfConverter",
    "CcdcClassification",
    "CcdcClassificationLookup",
    "CcdcWorkbookIndex",
    "FaGlLookup",
    "FaGlRecord",
    "FaGlWorkbookIndex",
    "TRAN_MAIL_HEADERS",
    "TRAN_SENT_HEADERS",
    "TRAN_YEAR_HEADERS",
    "TranMailDraftBuilder",
    "TranMailDraftResult",
    "TranMailError",
    "TranReferenceError",
    "TranWorkbookAdapter",
    "TranWorkbookError",
    "TranWorkbookExportResult",
    "build_tran_mail_table",
    "prepare_eml_bytes",
    "prepare_eml_document",
    "remaining_value_excel_formula",
]
